{% set name = "prettier" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: 95d9d6a95ff3e8eec383d2a7c23b0a497bface687e90e6a280823a942657f61a

build:
  number: 0

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - nodejs  # [not win]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"  # [not win]
    - prettier --version | findstr "{{ version }}"  # [win]
    - where prettier  # [win]

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - janjagusch
    - xhochy
    - pavelzw
    - JannikWibkerQC
